# Generated by Django 4.1.7 on 2023-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
